[uwsgi]
# Django-related settings
# the base directory (full path)
chdir = /root/venv/backstage
# Django's wsgi file
module = backstage.wsgi
# the virtualenv (full path)
home = /root/venv
# process-related settings
# master
master = true
# maximum number of worker processes
processes = 5
# the socket (use the full path to be safe
socket = 0.0.0.0:9000
# clear environment on exit
vacuum = true
#后台运行
uwsgidaemonize = yes
